<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class WCT_Admin {
    public static function init() {
        add_action('admin_menu',array(__CLASS__,'menu'));
        add_action('admin_post_wct_save_settings',array(__CLASS__,'save_settings'));
        add_action('admin_post_wct_delete_session',array(__CLASS__,'delete_session'));
        add_action('admin_enqueue_scripts',array(__CLASS__,'assets'));
    }
    public static function menu() {
        add_submenu_page('woocommerce','Checkout Sessions','Checkout Sessions','manage_woocommerce','wct-checkouts',array(__CLASS__,'page'));
        add_submenu_page('woocommerce','Checkout Tracker Settings','Checkout Tracker','manage_woocommerce','wct-settings',array(__CLASS__,'settings_page'));
    }
    public static function assets($hook) { if(strpos($hook,'wct-')===false) return; wp_enqueue_style('wct-admin',WCT_URL.'assets/css/admin.css',array(),WCT_VERSION); }
    private static function status_label($s){ return ucwords(str_replace('_',' ',$s)); }
    public static function page() {
        if(!current_user_can('manage_woocommerce')) return;
        global $wpdb; $st=WCT_DB::sessions_table(); $per=25; $page=max(1,absint($_GET['paged']??1)); $offset=($page-1)*$per;
        $status=sanitize_key($_GET['status']??''); $search=sanitize_text_field($_GET['s']??'');
        $where='WHERE 1=1'; $args=array(); if($status){$where.=' AND status=%s';$args[]=$status;} if($search){$where.=' AND (email LIKE %s OR phone LIKE %s OR customer_name LIKE %s OR session_key LIKE %s)';$q='%'.$wpdb->esc_like($search).'%';$args=array_merge($args,array($q,$q,$q,$q));}
        $count_sql="SELECT COUNT(*) FROM $st $where"; $total=(int)$wpdb->get_var($args?$wpdb->prepare($count_sql,$args):$count_sql);
        $args2=$args; $args2[]=$offset; $args2[]=$per; $rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM $st $where ORDER BY last_activity_at DESC LIMIT %d,%d",$args2));
        echo '<div class="wrap wct-wrap"><h1>WooCommerce Checkout Sessions</h1><p>Tracks checkout starts, field activity, cart snapshots and converted orders.</p>';
        echo '<div class="wct-cards">'; foreach(array('initiated','abandoned','converted') as $x){$n=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $st WHERE status=%s",$x)); echo '<div class="wct-card"><strong>'.esc_html(self::status_label($x)).'</strong><span>'.esc_html($n).'</span></div>'; } echo '</div>';
        echo '<form method="get" class="wct-filters"><input type="hidden" name="page" value="wct-checkouts"><input type="search" name="s" value="'.esc_attr($search).'" placeholder="Search name, phone, email, session..."><select name="status"><option value="">All statuses</option>'; foreach(array('initiated','abandoned','converted') as $x) echo '<option value="'.esc_attr($x).'" '.selected($status,$x,false).'>'.esc_html(self::status_label($x)).'</option>'; echo '</select><button class="button">Filter</button></form>';
        echo '<table class="widefat striped"><thead><tr><th>Session</th><th>Customer</th><th>Contact</th><th>Items</th><th>Total</th><th>Status</th><th>Last Activity</th><th>Order</th></tr></thead><tbody>';
        if(!$rows) echo '<tr><td colspan="8">No checkout sessions found.</td></tr>';
        foreach($rows as $r){echo '<tr><td><a href="'.esc_url(admin_url('admin.php?page=wct-checkouts&view='.absint($r->id))).'"><strong>'.esc_html($r->session_key).'</strong></a><br><small>'.esc_html(mysql2date(get_option('date_format').' '.get_option('time_format'),$r->started_at,true)).'</small></td><td>'.esc_html($r->customer_name?:'—').'</td><td>'.esc_html($r->email?:'—').'<br>'.esc_html($r->phone?:'').'</td><td>'.esc_html($r->item_count).'</td><td>'.wp_kses_post(wc_price((float)$r->cart_total,array('currency'=>$r->currency?:get_woocommerce_currency()))).'</td><td><span class="wct-status wct-'.esc_attr($r->status).'">'.esc_html(self::status_label($r->status)).'</span></td><td>'.esc_html(mysql2date(get_option('date_format').' '.get_option('time_format'),$r->last_activity_at,true)).'</td><td>'.($r->order_id?'<a href="'.esc_url(admin_url('post.php?post='.absint($r->order_id).'&action=edit')).'">#'.absint($r->order_id).'</a>':'—').'</td></tr>';}
        echo '</tbody></table>';
        $pages=max(1,ceil($total/$per)); if($pages>1) echo '<div class="tablenav"><div class="tablenav-pages">'.wp_kses_post(paginate_links(array('base'=>add_query_arg('paged','%#%'),'format'=>'','current'=>$page,'total'=>$pages,'type'=>'plain'))).'</div></div>';
        echo '</div>';
        if(isset($_GET['view'])) self::detail(absint($_GET['view']));
    }
    private static function detail($id){
        global $wpdb; $st=WCT_DB::sessions_table(); $ft=WCT_DB::fields_table(); $it=WCT_DB::items_table(); $r=$wpdb->get_row($wpdb->prepare("SELECT * FROM $st WHERE id=%d",$id)); if(!$r)return;
        $fields=$wpdb->get_results($wpdb->prepare("SELECT * FROM $ft WHERE session_id=%d ORDER BY field_key",$id)); $items=$wpdb->get_results($wpdb->prepare("SELECT * FROM $it WHERE session_id=%d ORDER BY id",$id));
        echo '<div class="wct-detail"><h2>Checkout Session #'.absint($r->id).'</h2><p><a href="'.esc_url(admin_url('admin.php?page=wct-checkouts')).'">← Back to sessions</a></p><div class="wct-grid"><div><h3>Session</h3><table class="form-table"><tr><th>Status</th><td>'.esc_html(self::status_label($r->status)).'</td></tr><tr><th>Session Key</th><td><code>'.esc_html($r->session_key).'</code></td></tr><tr><th>Started</th><td>'.esc_html($r->started_at).' UTC</td></tr><tr><th>Last Activity</th><td>'.esc_html($r->last_activity_at).' UTC</td></tr><tr><th>Converted</th><td>'.esc_html($r->converted_at?:'—').'</td></tr><tr><th>Order</th><td>'.($r->order_id?'<a href="'.esc_url(admin_url('post.php?post='.absint($r->order_id).'&action=edit')).'">#'.absint($r->order_id).'</a>':'—').'</td></tr></table></div><div><h3>Customer Summary</h3><table class="form-table"><tr><th>Name</th><td>'.esc_html($r->customer_name?:'—').'</td></tr><tr><th>Email</th><td>'.esc_html($r->email?:'—').'</td></tr><tr><th>Phone</th><td>'.esc_html($r->phone?:'—').'</td></tr><tr><th>Cart Total</th><td>'.wp_kses_post(wc_price((float)$r->cart_total,array('currency'=>$r->currency?:get_woocommerce_currency()))).'</td></tr><tr><th>Items Qty</th><td>'.esc_html($r->item_count).'</td></tr></table></div></div>';
        echo '<h3>Captured Checkout Fields</h3><table class="widefat striped"><thead><tr><th>Field</th><th>Value</th><th>Updated</th></tr></thead><tbody>'; foreach($fields as $f){echo '<tr><td><code>'.esc_html($f->field_key).'</code></td><td>'.nl2br(esc_html($f->field_value)).'</td><td>'.esc_html($f->updated_at).' UTC</td></tr>';} if(!$fields)echo'<tr><td colspan="3">No fields captured yet.</td></tr>'; echo '</tbody></table>';
        echo '<h3>Cart Snapshot</h3><table class="widefat striped"><thead><tr><th>Product</th><th>SKU</th><th>Qty</th><th>Unit Price</th><th>Line Total</th><th>Variation</th></tr></thead><tbody>'; foreach($items as $i){echo '<tr><td>'.esc_html($i->product_name).'</td><td>'.esc_html($i->sku?:'—').'</td><td>'.esc_html($i->quantity).'</td><td>'.wp_kses_post(wc_price((float)$i->unit_price)).'</td><td>'.wp_kses_post(wc_price((float)$i->line_total)).'</td><td><code>'.esc_html($i->variation_json?:'—').'</code></td></tr>';} if(!$items)echo'<tr><td colspan="6">No cart items.</td></tr>'; echo '</tbody></table></div>';
    }
    public static function settings_page(){ if(!current_user_can('manage_woocommerce'))return; $s=wp_parse_args(get_option('wct_settings',array()),array('enabled'=>1,'retention_days'=>90,'abandon_timeout_minutes'=>60,'email_alerts_enabled'=>0,'email_alert_recipients'=>get_option('admin_email'))); echo '<div class="wrap wct-wrap"><h1>Checkout Tracker Settings</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="wct_save_settings">'.wp_nonce_field('wct_settings','wct_nonce',true,false).'<table class="form-table"><tr><th>Capture checkout sessions</th><td><label><input type="checkbox" name="enabled" value="1" '.checked(!empty($s['enabled']),true,false).'> Enable tracking</label><p class="description">Tracks checkout page activity for users who interact with the checkout.</p></td></tr><tr><th>Abandoned checkout timeout</th><td><input type="number" min="5" max="10080" name="abandon_timeout_minutes" value="'.esc_attr($s['abandon_timeout_minutes']).'"> minutes <p class="description">An Initiated session is marked Abandoned when there has been no checkout activity for this period. The scheduled task runs every 15 minutes.</p></td></tr><tr><th>Abandoned email alerts</th><td><label><input type="checkbox" name="email_alerts_enabled" value="1" '.checked(!empty($s['email_alerts_enabled']),true,false).'> Send an email when a session becomes Abandoned</label><p><input type="text" class="regular-text" name="email_alert_recipients" value="'.esc_attr($s['email_alert_recipients']).'" placeholder="admin@example.com, sales@example.com"></p><p class="description">Enter one or more recipient email addresses separated by commas, semicolons, or spaces. Alerts include customer details, captured checkout fields, cart items, total, and a WP-Admin session link. Emails are sent by WordPress wp_mail().</p></td></tr><tr><th>Retention (days)</th><td><input type="number" min="1" max="3650" name="retention_days" value="'.esc_attr($s['retention_days']).'"> <p class="description">Old session records are removed by the scheduled maintenance task. IP is stored only as a one-way hash.</p></td></tr></table><p><button class="button button-primary">Save Settings</button></p></form><hr><h2>Data captured</h2><p>Checkout form values except payment/security-sensitive fields, cart products, quantities, prices, variations, session timestamps, and conversion order ID.</p><p><strong>Privacy:</strong> Add appropriate disclosure/consent to your site according to your local privacy requirements. Do not use this tracker to collect card numbers, CVV/CVC, passwords, or payment tokens.</p></div>'; }
    public static function save_settings(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('wct_settings','wct_nonce'))wp_die('Unauthorized.');$recipients = isset($_POST['email_alert_recipients']) ? sanitize_text_field(wp_unslash($_POST['email_alert_recipients'])) : get_option('admin_email'); update_option('wct_settings',array('enabled'=>empty($_POST['enabled'])?0:1,'abandon_timeout_minutes'=>min(10080,max(5,absint($_POST['abandon_timeout_minutes']??60))),'retention_days'=>min(3650,max(1,absint($_POST['retention_days']??90))),'email_alerts_enabled'=>empty($_POST['email_alerts_enabled'])?0:1,'email_alert_recipients'=>$recipients));WCT_Tracker::reschedule();wp_safe_redirect(admin_url('admin.php?page=wct-settings&updated=1'));exit;}
    public static function delete_session(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('wct_delete','wct_nonce'))wp_die('Unauthorized.');$id=absint($_GET['id']??0);global $wpdb;$wpdb->delete(WCT_DB::fields_table(),array('session_id'=>$id));$wpdb->delete(WCT_DB::items_table(),array('session_id'=>$id));$wpdb->delete(WCT_DB::sessions_table(),array('id'=>$id));wp_safe_redirect(admin_url('admin.php?page=wct-checkouts'));exit;}
}
